"""Regenerate the data baked into ``tutorial/index.html``.

The tutorial computes almost everything in the browser, but the solution-count
table for larger ``n`` is too slow to enumerate client-side. Those numbers are
pre-computed here with the repo's own solver so the tutorial can never drift from
the real algorithm.

Usage::

    python -m src.build_tutorial            # n = 8 .. 60
    python -m src.build_tutorial --max 72   # extend the table (slow past ~62)

Commit the updated ``tutorial/index.html`` afterwards.
"""

from __future__ import annotations

import argparse
import re
import time
from pathlib import Path

from src.pair_solver import count_solutions

TUTORIAL = Path(__file__).resolve().parent.parent / "tutorial" / "index.html"
BLOCK = re.compile(
    r"(  // >>> AUTO-GENERATED by [^\n]*\n)"
    r".*?"
    r"(  // <<< AUTO-GENERATED\n)",
    re.DOTALL,
)


def solution_counts(max_n: int) -> list[tuple[int, int]]:
    counts: list[tuple[int, int]] = []
    for n in range(8, max_n + 1, 2):
        t = time.time()
        try:
            c = count_solutions(n)
        except ValueError:
            c = 0  # some vertex has no square-sum partner -> no matching
        counts.append((n, c))
        print(f"  n={n:>3}  solutions={c:<12,}  ({time.time() - t:.1f}s)")
    return counts


def render_block(counts: list[tuple[int, int]]) -> str:
    lines = ["  const COUNTS = ["]
    for i in range(0, len(counts), 7):
        chunk = counts[i : i + 7]
        lines.append("    " + ", ".join(f"[{n}, {c}]" for n, c in chunk) + ",")
    lines.append("  ];")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--max", type=int, default=60, help="largest even n to include (default 60)")
    args = ap.parse_args(argv)

    if not TUTORIAL.exists():
        raise SystemExit(f"not found: {TUTORIAL}")

    print(f"Computing solution counts up to n={args.max} ...")
    counts = solution_counts(args.max)

    html = TUTORIAL.read_text()
    if not BLOCK.search(html):
        raise SystemExit("AUTO-GENERATED markers not found in tutorial/index.html")

    new = BLOCK.sub(lambda m: m.group(1) + render_block(counts) + m.group(2), html, count=1)
    if new == html:
        print("tutorial/index.html already up to date.")
        return 0
    TUTORIAL.write_text(new)
    print(f"Updated {TUTORIAL} ({len(counts)} rows).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
